# Generated by Django 3.0.6 on 2020-07-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200707_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicinfo',
            name='image',
        ),
        migrations.AddField(
            model_name='musicinfo',
            name='band',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
