# Generated by Django 3.0.6 on 2020-06-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200630_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicinfo',
            name='year',
            field=models.DateField(verbose_name='yyyy'),
        ),
    ]
