# Generated by Django 3.0.6 on 2020-07-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200715_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicinfo',
            name='description',
            field=models.TextField(),
        ),
    ]
